### PR TITLE
Exercise

### PR DESCRIPTION
**Pull request by SMITHsharon**
justinal64
Have created four cards, which are really just copies of the first to serve for now as placeholders. Will change content when the styling issue is resolved. 

The four cards display in a single column, as block elements. 
When I added the line <display: inline-flex> to my css file to the #card, 
the cards display inline, but also their contents. Cannot find how to grab only the containers, 
but leave the contents unchanged ? 

Apart from that, I think this assignment is close to done.

### CODE REVIEW

**Comment by justinal64** [comment]
@SMITHsharon Looks good. Do you want to talk about how to fix the problem before you merge it in?

**Comment by SMITHsharon** [comment]
This is not correct yet, so not ready to merge in. 
Still working on it. I created a <grid> container for the cards, so that was the biggest problem. Now working on the next layer of problems, which I think should be easier to resolve.

**Comment by SMITHsharon** [comment]
justinal64
questions : / 
* Applied flexbox, and have a statement <flex-basis: 30%;> that I think should give each Card 30% of the width of the window, so three cards across, but there are four cards across ? 
* On the spec, the gray bar for the Available band stretches all the way across to the card edge ? 
* It looks like to me, everything for my Specifications and Pricing is structured exactly the same, in both the html and css, but the formatting is not being recognized for Pricing. Also, in Developer Tools, don't understand why some of the css statements aren't recognized ? 

I think if I fix these, all I have to do is drop in some content and this assignment is done

**Comment by SMITHsharon** [comment]
@justinal64 :: totally done with the Product Cards assignment
#woot #manyThanks for your help this morning ;)

**Comment by justinal64** [comment]
@SMITHsharon  Everything looks great. Sorry I didn't comment on this earlier I though you were going to merge your PR.

**Pull request merged**
